version: '1.0'
name: electron-build-pipeline
displayName: Electron应用构建流水线
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''

stages:
  - name: build_stage
    displayName: 构建阶段
    strategy: naturally
    trigger: auto
    steps:
        - step: build@npm
          name: build_windows
          displayName: 构建 Windows 版本
          tags:
            - windows
          inputs:
            npmRegistry: https://registry.npmmirror.com
            command: npm install && rm -rf ./dist_win && npm run build:win
            artifactBuildPath:
              - name: BUILD_ARTIFACT_WIN
                path:
                  - ./release
                type: .tar.gz
          artifacts:
            paths:
              - release/*.exe
              - release/*.zip
            expire_in: 7 days

        - step: build@npm
          name: build_macos
          displayName: 构建 macOS 版本
          tags:
            - macos
          inputs:
            npmRegistry: https://registry.npmmirror.com
            command: npm install && rm -rf ./dist_mac && npm run build:mac
            artifactBuildPath:
              - name: BUILD_ARTIFACT_MAC
                path:
                  - ./release
                type: .tar.gz
          artifacts:
            paths:
              - release/*.dmg
              - release/*.zip
            expire_in: 7 days

        - step: build@npm
          name: build_linux
          displayName: 构建 Linux 版本
          tags:
            - linux
          inputs:
            npmRegistry: https://registry.npmmirror.com
            command: npm install && rm -rf ./dist_linux && npm run build:linux
            artifactBuildPath:
              - name: BUILD_ARTIFACT_LINUX
                path:
                  - ./release
                type: .tar.gz
          artifacts:
            paths:
              - release/*.AppImage
              - release/*.deb
              - release/*.zip
            expire_in: 7 days
